services:
  - type: web
    name: contactdiary
    runtime: docker
    plan: free
    healthCheckPath: /app.html
    autoDeploy: true
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_SMTP_AUTH
        value: "true"
      - key: MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
